name: Simple Versioned Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Update Version in pyproject.toml
        run: |
          sed -i "s/^version = .*/version = \"${RELEASE_VERSION}\"/" pyproject.toml
      
      - name: Commit Version Update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Update version to ${RELEASE_VERSION} in pyproject.toml"
          git push origin:HEAD