name: Simple Versioned Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Update Version in pyproject.toml
        run: |
          FORMATTED_RELEASE_VERSION=${RELEASE_VERSION#v}
          sed -i "s/^version = .*/version = \"${FORMATTED_RELEASE_VERSION}\"/" pyproject.toml
      
      - name: Commit Version Update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Update version to ${RELEASE_VERSION} in pyproject.toml"
          git push origin HEAD:main

  release:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ env.RELEASE_VERSION }}
            release_name: "Release ${{ env.RELEASE_VERSION }}"
            body: ${{ github.event.head_commit.message }}
            draft: false
            prerelease: false