name: Simple Versioned Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve Git Tag
        run: |
          TAG=$(git describe --tags)
          
          